-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH,CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) BETWEEN 08 AND 10 AND CAR_ID in (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE MONTH(START_DATE) BETWEEN 08 AND 10 GROUP BY car_id HAVING COUNT(history_id)>4) 
GROUP BY MONTH(START_DATE),CAR_ID
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC